spring:
  application:
    name: replication
  datasource:
    source:
      jdbc-url: jdbc:mysql://localhost:3306/mydb
      username: myuser
      password: mypassword
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      jdbc-url: jdbc:mysql://localhost:3307/mydb
      username: myuser
      password: mypassword
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect